/*
 * ULTRASONIC_CONFIGURATION.h
 *
 * Created: 3/9/2022 5:00:38 PM
 *  Author: alkods
 */ 


#ifndef ULTRASONIC_CONFIGURATION_H_
#define ULTRASONIC_CONFIGURATION_H_


#define TRIGGER_DDR		DIO_PORTD
#define ECHO_DDR		DIO_PORTD
#define TRIGGER_PORT	DIO_PORTD
#define ECHO_PORT		DIO_PORTD
#define TRIGGER			DIO_PIN0
#define	ECHO			DIO_PIN2


#endif /* ULTRASONIC_CONFIGURATION_H_ */