/*
 * EXTERNAL_INT_CONFIGURATION.h
 *
 * Created: 2/13/2022 5:16:23 PM
 *  Author: alkods
 */ 


#ifndef EXTERNAL_INT_CONFIGURATION_H_
#define EXTERNAL_INT_CONFIGURATION_H_





#define			EXTERNAL_INT0_TRIGGER_MODE			ANY_LOGICAL_CHANGE
#define			EXTERNAL_INT1_TRIGGER_MODE			ANY_LOGICAL_CHANGE
#define			EXTERNAL_INT2_TRIGGER_MODE			FALLING_EDGE_MODE


#endif /* EXTERNAL_INT_CONFIGURATION_H_ */