/*
 * EXTERNAL_INT.c
 *
 * Created: 2/13/2022 5:17:05 PM
 *  Author: alkods
 */ 


#include "EXTERNAL_INT.h"

uint8 EXTERNAL_INT0_TRIGGER_MODE = ANY_LOGICAL_CHANGE;
uint8 EXTERNAL_INT1_TRIGGER_MODE = ANY_LOGICAL_CHANGE;
uint8 EXTERNAL_INT2_TRIGGER_MODE = FALLING_EDGE_MODE;


void EXT_INT_SELECT_TRIGGER_MODE(uint8 INT_0, uint8 INT_1, uint8 INT_2)
{
	EXTERNAL_INT0_TRIGGER_MODE = INT_0;  
	EXTERNAL_INT1_TRIGGER_MODE = INT_1;
	EXTERNAL_INT2_TRIGGER_MODE = INT_2;
}

void SET_GLOBAL_INT(void)
{
	SET_BIT(SREG, 7);
}

void EXTERNAL_INT0_INIT(void)
{
	SET_GLOBAL_INT();
	SET_BIT(GICR, 6);
	if	(EXTERNAL_INT0_TRIGGER_MODE == LOW_LEVEL_MODE)
	{
	CLR_BIT(MCUCR, 0);
	CLR_BIT(MCUCR, 1);
	}
	else if	(EXTERNAL_INT0_TRIGGER_MODE == ANY_LOGICAL_CHANGE)
	{
	SET_BIT(MCUCR, 0);
	CLR_BIT(MCUCR, 1);
	}
	else if	(EXTERNAL_INT0_TRIGGER_MODE == FALLING_EDGE_MODE)
	{
	CLR_BIT(MCUCR, 0);
	SET_BIT(MCUCR, 1);
	}
	else if	(EXTERNAL_INT0_TRIGGER_MODE == RISING_EDGE_MODE)
	{
	SET_BIT(MCUCR, 0);
	SET_BIT(MCUCR, 1);
	}
}

void EXTERNAL_INT1_INIT(void)
{
	SET_GLOBAL_INT();
	SET_BIT(GICR, 7);
	if	(EXTERNAL_INT1_TRIGGER_MODE == LOW_LEVEL_MODE)
	{
		CLR_BIT(MCUCR, 2);
		CLR_BIT(MCUCR, 3);
	}
	else if	(EXTERNAL_INT1_TRIGGER_MODE == ANY_LOGICAL_CHANGE)
	{
		SET_BIT(MCUCR, 2);
		CLR_BIT(MCUCR, 3);
	}
	else if	(EXTERNAL_INT1_TRIGGER_MODE == FALLING_EDGE_MODE)
	{
		CLR_BIT(MCUCR, 2);
		SET_BIT(MCUCR, 3);
	}
	else if	(EXTERNAL_INT1_TRIGGER_MODE == RISING_EDGE_MODE)
	{
		SET_BIT(MCUCR, 2);
		SET_BIT(MCUCR, 3);
	}
}




void EXTERNAL_INT2_INIT(void)
{
	SET_GLOBAL_INT();
	SET_BIT(GICR, 5);
	if (EXTERNAL_INT2_TRIGGER_MODE == FALLING_EDGE_MODE)
	{
	CLR_BIT(MCUCSR, 6);
	}
	else if (EXTERNAL_INT2_TRIGGER_MODE == RISING_EDGE_MODE)
	{
	SET_BIT(MCUCSR, 6);
	}
}

void (*CALLBACK_PTR_INT_0) (void) = 0;

void EXTERNAL_INIT0_SET_CALLBACK( void (*COPY_FUNCTION) (void))
{
	CALLBACK_PTR_INT_0 = COPY_FUNCTION;
	
}

ISR(INT0_vect)
{
	if(CALLBACK_PTR_INT_0 != 0)
	{
		CALLBACK_PTR_INT_0();
	}
}

void (*CALLBACK_PTR_INT_1) (void) = 0;

void EXTERNAL_INIT1_SET_CALLBACK( void (*COPY_FUNCTION) (void))
{
	CALLBACK_PTR_INT_1 = COPY_FUNCTION;
	
}

ISR(INT1_vect)
{
	if(CALLBACK_PTR_INT_1 != 0)
	{
		CALLBACK_PTR_INT_1();
	}
}